<?php

namespace Database\Seeders;

use App\Models\Drink;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DrinkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drinks = [
            [
                'name' => 'Espresso',
                'name_ru' => 'Эспрессо',
                'name_en' => 'Espresso',
                'cafeteria_id' => 1,
                'category_id' => 1,
                'image' => 'drinks/espresso.jpg',
                'price' => 20.00,
                'description' => 'Güyçli we goýy adaty kofe içgisi.',
                'description_ru' => 'Крепкий и насыщенный классический кофе.',
                'description_en' => 'Strong and rich classic coffee.',
                'weight' => '30 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Amerikano',
                'name_ru' => 'Американо',
                'name_en' => 'Americano',
                'cafeteria_id' => 1,
                'category_id' => 1,
                'image' => 'drinks/americano.jpg',
                'price' => 25.00,
                'description' => 'Yssy suw goşulan ýumşak espresso.',
                'description_ru' => 'Мягкий эспрессо с добавлением горячей воды.',
                'description_en' => 'Smooth espresso diluted with hot water.',
                'weight' => '200 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Kapuçino',
                'name_ru' => 'Капучино',
                'name_en' => 'Cappuccino',
                'cafeteria_id' => 2,
                'category_id' => 1,
                'image' => 'drinks/cappuccino.jpg',
                'price' => 35.00,
                'description' => 'Süýt köpürjigi we espresso garyşygy.',
                'description_ru' => 'Сбалансированное сочетание эспрессо и молочной пены.',
                'description_en' => 'Balanced mixture of espresso and foamed milk.',
                'weight' => '250 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Latte',
                'name_ru' => 'Латте',
                'name_en' => 'Latte',
                'cafeteria_id' => 2,
                'category_id' => 1,
                'image' => 'drinks/latte.jpg',
                'price' => 38.00,
                'description' => 'Názik süýtli kofe içgisi.',
                'description_ru' => 'Нежный кофейный напиток с большим количеством молока.',
                'description_en' => 'Delicate coffee drink with plenty of milk.',
                'weight' => '300 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Flat White',
                'name_ru' => 'Флэт Уайт',
                'name_en' => 'Flat White',
                'cafeteria_id' => 3,
                'category_id' => 1,
                'image' => 'drinks/flat_white.jpg',
                'price' => 40.00,
                'description' => 'Goşa espresso we ýuka süýt köpürjigi.',
                'description_ru' => 'Двойной эспрессо с тонким слоем бархатистой пены.',
                'description_en' => 'Double espresso with a thin layer of velvety foam.',
                'weight' => '200 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Raf Kofe',
                'name_ru' => 'Раф кофе',
                'name_en' => 'Raf Coffee',
                'cafeteria_id' => 3,
                'category_id' => 1,
                'image' => 'drinks/raf.jpg',
                'price' => 45.00,
                'description' => 'Gaimak we wanil şekerli tatar kofe.',
                'description_ru' => 'Кофе со сливками и ванильным сахаром.',
                'description_en' => 'Coffee whipped with cream and vanilla sugar.',
                'weight' => '250 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Mokka',
                'name_ru' => 'Мокка',
                'name_en' => 'Mocha',
                'cafeteria_id' => 4,
                'category_id' => 1,
                'image' => 'drinks/mocha.jpg',
                'price' => 42.00,
                'description' => 'Şokolad we espresso garyşykly süýtli kofe.',
                'description_ru' => 'Кофейно-молочный напиток с шоколадным вкусом.',
                'description_en' => 'Coffee drink with milk and chocolate flavor.',
                'weight' => '300 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Karamel Makkiato',
                'name_ru' => 'Карамель Макиато',
                'name_en' => 'Caramel Macchiato',
                'cafeteria_id' => 4,
                'category_id' => 1,
                'image' => 'drinks/caramel_macchiato.jpg',
                'price' => 48.00,
                'description' => 'Karamel siroply we süýtli kofe.',
                'description_ru' => 'Эспрессо с молоком и карамельным сиропом.',
                'description_en' => 'Espresso with milk and caramel syrup.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Gök Çaý',
                'name_ru' => 'Зеленый чай',
                'name_en' => 'Green Tea',
                'cafeteria_id' => 5,
                'category_id' => 2,
                'image' => 'drinks/green_tea.jpg',
                'price' => 15.00,
                'description' => 'Adaty arassa gök çaý.',
                'description_ru' => 'Традиционный чистый зеленый чай.',
                'description_en' => 'Traditional pure green tea.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Gara Çaý',
                'name_ru' => 'Черный чай',
                'name_en' => 'Black Tea',
                'cafeteria_id' => 5,
                'category_id' => 2,
                'image' => 'drinks/black_tea.jpg',
                'price' => 15.00,
                'description' => 'Klassiki gara çaý.',
                'description_ru' => 'Классический листовой черный чай.',
                'description_en' => 'Classic loose-leaf black tea.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Jasminli Gök Çaý',
                'name_ru' => 'Зеленый чай с жасмином',
                'name_en' => 'Jasmine Green Tea',
                'cafeteria_id' => 6,
                'category_id' => 2,
                'image' => 'drinks/jasmine_tea.jpg',
                'price' => 22.00,
                'description' => 'Jasmin gülleriniň ýakymly ysy bar bolan çaý.',
                'description_ru' => 'Ароматный зеленый чай с лепестками жасмина.',
                'description_en' => 'Aromatic green tea with jasmine petals.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Limonly Çaý',
                'name_ru' => 'Чай с лимоном',
                'name_en' => 'Lemon Tea',
                'cafeteria_id' => 6,
                'category_id' => 2,
                'image' => 'drinks/lemon_tea.jpg',
                'price' => 20.00,
                'description' => 'Täze kesilen limonly gara çaý.',
                'description_ru' => 'Черный чай со свежими дольками лимона.',
                'description_en' => 'Black tea served with fresh lemon slices.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Ananas we Narpyzly Çaý',
                'name_ru' => 'Фруктовый чай с ананасом и мятой',
                'name_en' => 'Pineapple & Mint Tea',
                'cafeteria_id' => 7,
                'category_id' => 2,
                'image' => 'drinks/fruit_tea.jpg',
                'price' => 30.00,
                'description' => 'Mire-miweli we narpyzly yssy çaý.',
                'description_ru' => 'Горячий авторский чай с ананасом и мятой.',
                'description_en' => 'Hot signature tea with pineapple and fresh mint.',
                'weight' => '500 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Imbirli we Bally Çaý',
                'name_ru' => 'Имбирный чай с медом',
                'name_en' => 'Ginger Honey Tea',
                'cafeteria_id' => 7,
                'category_id' => 2,
                'image' => 'drinks/ginger_tea.jpg',
                'price' => 32.00,
                'description' => 'Saglyga peýdaly imbir, bal we limonly çaý.',
                'description_ru' => 'Полезный согревающий чай с имбирем, медом и лимоном.',
                'description_en' => 'Healthy warming tea with ginger, honey, and lemon.',
                'weight' => '500 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Klassiki Limonad',
                'name_ru' => 'Классический лимонад',
                'name_en' => 'Classic Lemonade',
                'cafeteria_id' => 8,
                'category_id' => 3,
                'image' => 'drinks/classic_lemonade.jpg',
                'price' => 25.00,
                'description' => 'Limon şiresi we buzly serginlediji içgi.',
                'description_ru' => 'Освежающий цитрусовый лимонад со льдом.',
                'description_en' => 'Refreshing citrus lemonade served with ice.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Ýertutanly Limonad',
                'name_ru' => 'Клубничный лимонад',
                'name_en' => 'Strawberry Lemonade',
                'cafeteria_id' => 8,
                'category_id' => 3,
                'image' => 'drinks/strawberry_lemonade.jpg',
                'price' => 30.00,
                'description' => 'Täze ýertutan miweli serginlediji limonad.',
                'description_ru' => 'Домашний лимонад со свежей клубникой.',
                'description_en' => 'Homemade lemonade with fresh strawberries.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Mohito (Spirtsiz)',
                'name_ru' => 'Мохито (безалкогольный)',
                'name_en' => 'Mojito (Virgin)',
                'cafeteria_id' => 1,
                'category_id' => 3,
                'image' => 'drinks/mojito.jpg',
                'price' => 35.00,
                'description' => 'Laým, narpyz we gazly suw garyşygy.',
                'description_ru' => 'Освежающий коктейль с лаймом, мятой и содовой.',
                'description_en' => 'Refreshing cocktail with lime, mint, and soda.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Aýs Amerikano',
                'name_ru' => 'Айс Американо',
                'name_en' => 'Iced Americano',
                'cafeteria_id' => 2,
                'category_id' => 3,
                'image' => 'drinks/ice_americano.jpg',
                'price' => 28.00,
                'description' => 'Buzly salkyn amerikano kofesi.',
                'description_ru' => 'Холодный американо со льдом.',
                'description_en' => 'Chilled americano over ice.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Aýs Latte',
                'name_ru' => 'Айс Латте',
                'name_en' => 'Iced Latte',
                'cafeteria_id' => 3,
                'category_id' => 3,
                'image' => 'drinks/ice_latte.jpg',
                'price' => 40.00,
                'description' => 'Buzly we süýtli salkyn kofe.',
                'description_ru' => 'Холодный кофейно-молочный напиток со льдом.',
                'description_en' => 'Chilled coffee drink with milk and ice.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Bumble Coffee',
                'name_ru' => 'Бамбл кофе',
                'name_en' => 'Bumble Coffee',
                'cafeteria_id' => 4,
                'category_id' => 3,
                'image' => 'drinks/bumble.jpg',
                'price' => 45.00,
                'description' => 'Portakal şiresi, espresso we karamel siropy.',
                'description_ru' => 'Слоистый напиток из апельсинового сока, эспрессо и карамели.',
                'description_en' => 'Layered drink of orange juice, espresso, and caramel syrup.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Wanil Milkşeýk',
                'name_ru' => 'Ванильный милкшейк',
                'name_en' => 'Vanilla Milkshake',
                'cafeteria_id' => 5,
                'category_id' => 4,
                'image' => 'drinks/vanilla_shake.jpg',
                'price' => 35.00,
                'description' => 'Wanil doňdurmasy we süýtli kokteýl.',
                'description_ru' => 'Густой молочный коктейль с ванильным мороженым.',
                'description_en' => 'Thick milkshake made with vanilla ice cream.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Şokoladly Milkşeýk',
                'name_ru' => 'Шоколадный милкшейк',
                'name_en' => 'Chocolate Milkshake',
                'cafeteria_id' => 6,
                'category_id' => 4,
                'image' => 'drinks/chocolate_shake.jpg',
                'price' => 35.00,
                'description' => 'Şokolad doňdurmasy we süýtli kokteýl.',
                'description_ru' => 'Густой молочный коктейль с шоколадным вкусом.',
                'description_en' => 'Rich milkshake with chocolate ice cream.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Ýertutanly Milkşeýk',
                'name_ru' => 'Клубничный милкшейк',
                'name_en' => 'Strawberry Milkshake',
                'cafeteria_id' => 7,
                'category_id' => 4,
                'image' => 'drinks/strawberry_shake.jpg',
                'price' => 38.00,
                'description' => 'Täze ýertutan we süýt garyşygy.',
                'description_ru' => 'Молочный коктейль с натуральным клубничным пюре.',
                'description_en' => 'Milkshake made with natural strawberry puree.',
                'weight' => '350 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Oreo Milkşeýk',
                'name_ru' => 'Милкшейк Орео',
                'name_en' => 'Oreo Milkshake',
                'cafeteria_id' => 8,
                'category_id' => 4,
                'image' => 'drinks/oreo_shake.jpg',
                'price' => 42.00,
                'description' => 'Oreo peçenyesi goşulan süýtli kokteýl.',
                'description_ru' => 'Молочный коктейль с кусочками печенья Oreo.',
                'description_en' => 'Milkshake blended with crispy Oreo cookies.',
                'weight' => '400 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Portakal Şiresi',
                'name_ru' => 'Апельсиновый сок',
                'name_en' => 'Orange Juice',
                'cafeteria_id' => 1,
                'category_id' => 5,
                'image' => 'drinks/orange_juice.jpg',
                'price' => 30.00,
                'description' => 'Täze sıkylan arassa portakal şiresi.',
                'description_ru' => 'Свежевыжатый апельсиновый сок.',
                'description_en' => 'Freshly squeezed orange juice.',
                'weight' => '250 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Alma Şiresi',
                'name_ru' => 'Яблочный сок',
                'name_en' => 'Apple Juice',
                'cafeteria_id' => 2,
                'category_id' => 5,
                'image' => 'drinks/apple_juice.jpg',
                'price' => 25.00,
                'description' => 'Täze sıkylan alma şiresi.',
                'description_ru' => 'Свежевыжатый яблочный сок.',
                'description_en' => 'Freshly squeezed apple juice.',
                'weight' => '250 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Nar Şiresi',
                'name_ru' => 'Гранатовый сок',
                'name_en' => 'Pomegranate Juice',
                'cafeteria_id' => 3,
                'category_id' => 5,
                'image' => 'drinks/pomegranate_juice.jpg',
                'price' => 35.00,
                'description' => 'Täze sıkylan nar şiresi.',
                'description_ru' => 'Натуральный свежевыжатый гранатовый сок.',
                'description_en' => 'Natural freshly squeezed pomegranate juice.',
                'weight' => '250 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Gazsyz Suw',
                'name_ru' => 'Вода без газа',
                'name_en' => 'Still Water',
                'cafeteria_id' => 4,
                'category_id' => 5,
                'image' => 'drinks/water.jpg',
                'price' => 5.00,
                'description' => 'Arassa agyz suwy.',
                'description_ru' => 'Очищенная питьевая негазированная вода.',
                'description_en' => 'Purified still drinking water.',
                'weight' => '500 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Gazly Suw',
                'name_ru' => 'Газированная вода',
                'name_en' => 'Sparkling Water',
                'cafeteria_id' => 5,
                'category_id' => 5,
                'image' => 'drinks/sparkling_water.jpg',
                'price' => 15.00,
                'description' => 'Tabigy mineral gazly suw.',
                'description_ru' => 'Природная газированная минеральная вода.',
                'description_en' => 'Natural sparkling mineral water.',
                'weight' => '500 ml',
                'is_available' => true,
            ],
            [
                'name' => 'Yssy Şokolad',
                'name_ru' => 'Горячий шоколад',
                'name_en' => 'Hot Chocolate',
                'cafeteria_id' => 6,
                'category_id' => 1,
                'image' => 'drinks/hot_chocolate.jpg',
                'price' => 35.00,
                'description' => 'Goýy we süýji yssy şokolad içgisi.',
                'description_ru' => 'Густой и насыщенный горячий шоколад.',
                'description_en' => 'Thick and rich hot chocolate drink.',
                'weight' => '200 ml',
                'is_available' => true,
            ],
        ];

        foreach ($drinks as $drink) {
            Drink::create($drink);
        }
    }
}
